// Dữ liệu kế hoạch tuần - Dự án Talent25 - Nhóm 5TING
// Nguồn: New Text Document.txt
const MEMBER_TASKS_RAW = [
  {"row_number":4,"date":"01–05/01/2026","col_2":"Tuần 1","col_3":"Kick-off dự án, xác định vị trí ứng dụng","col_4":"Khương Đức Tình","col_6":"Hoàn thành","col_7":"Phân loại linh kiện nhựa & silicone tiếp xúc nước"},
  {"row_number":5,"date":"06–12/01/2026","col_2":"Tuần 2","col_3":"Nghiên cứu công nghệ kháng khuẩn & NSF","col_4":"Khương Đức Tình","col_6":"Hoàn thành","col_7":"Phân tích hàm lượng nano Ag, NSF 58/61"},
  {"row_number":6,"date":"13–19/01/2026","col_2":"Tuần 3","col_3":"Benchmark & tiêu chí chọn NCC, Lập DFMEA","col_4":"Khương Đức Tình","col_6":"Hoàn thành","col_7":"Lập checklist hồ sơ & năng lực NCC phân phối linh kiện"},
  {"row_number":7,"date":"20–31/01/2026","col_2":"Tuần 4","col_3":"Chốt yêu cầu kỹ thuật, tham khảo các bộ phận chức năng khác","col_4":"Khương Đức Tình","col_6":"Hoàn thành","col_7":"Đã trao đổi với NCC để đặt mua hàng theo luồng KO APR32253. Thúc đẩy NCC chuyển hàng trước tết."},
  {"row_number":8,"date":"01–07/02/2026","col_2":"Tuần 5","col_3":"Tìm kiếm NCC nhựa & silicone. Tìm kiếm đơn vị phân tích vi sinh.","col_4":"Khương Đức Tình","col_6":"Đang thực hiện","col_7":""},
  {"row_number":9,"date":"08–14/02/2026","col_2":"Tuần 6","col_3":"Lập mindmap đánh giá thử nghiệm. Gửi mẫu đánh giá cho DQA và NCTN","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":10,"date":"22–29/02/2026","col_2":"Tuần 8","col_3":"Tổng hợp báo cáo, test các hạng mục rủi ro cao.","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":11,"date":"01–07/03/2026","col_2":"Tuần 9","col_3":"Lắp linh kiện trên máy M25 đánh giá cụ thể","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":12,"date":"08–14/03/2026","col_2":"Tuần 10","col_3":"Ngâm mẫu nhựa & silicone theo thời gian","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":13,"date":"15–21/03/2026","col_2":"Tuần 11","col_3":"Lắp máy M25 sử dụng nhựa/silicone để uống trải nghiệm hàng ngày","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":14,"date":"22–31/03/2026","col_2":"Tuần 12","col_3":"Thu thập dữ liệu phản hồi về màu, mùi vị khi sử dụng linh kiện. Lập TCKT","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":15,"date":"01–07/04/2026","col_2":"Tuần 13","col_3":"Test kháng khuẩn ban đầu. Ban hành TCKT, cài giá trên SAP","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":16,"date":"08–14/04/2026","col_2":"Tuần 14","col_3":"Chạy máy mốc 1 tháng.","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":17,"date":"15–21/04/2026","col_2":"Tuần 15","col_3":"Test kháng khuẩn sau 1 tháng","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":18,"date":"22–30/04/2026","col_2":"Tuần 16","col_3":"Tổng hợp kết quả phân tích và bảng đánh giá trải nghiệm máy.","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":19,"date":"01–07/05/2026","col_2":"Tuần 17","col_3":"Ban hành ECN chuyển đổi. Đề xuất KHSX lên lịch đặt hàng","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":20,"date":"08–14/05/2026","col_2":"Tuần 18","col_3":"Chạy lô T0","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":21,"date":"15–21/05/2026","col_2":"Tuần 19","col_3":"Đánh giá T0 cho NCTN và DQA","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":22,"date":"22–31/05/2026","col_2":"Tuần 20","col_3":"Lên lịch sản xuất chạy lô T1.","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":23,"date":"01–07/06/2026","col_2":"Tuần 21","col_3":"Chạy lô T1","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":24,"date":"08–14/06/2026","col_2":"Tuần 22","col_3":"Đánh giá lô T1","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":25,"date":"15–21/06/2026","col_2":"Tuần 23","col_3":"Hoàn thiện hồ sơ sản xuất","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":26,"date":"22–30/06/2026","col_2":"Tuần 24","col_3":"Chuyển giao hồ sơ xuống nhà máy.","col_4":"Khương Đức Tình","col_6":"","col_7":""},
  {"row_number":27,"date":"01–05/01","col_2":"Tuần 1","col_3":"Kick-off dự án, xác định vật liệu, thu thập dữ liệu về Ionpure","col_4":"Đào Hoàng Dương","col_6":"Hoàn thành","col_7":"Tìm hiểu tính khả thi, dữ liêu phân tích liên quan"},
  {"row_number":28,"date":"06–12/01","col_2":"Tuần 2","col_3":"Nghiên cứu cơ chế Ionpure, benchmark","col_4":"Đào Hoàng Dương","col_6":"Hoàn thành","col_7":"Báo cáo công nghệ"},
  {"row_number":29,"date":"13–19/01","col_2":"Tuần 3","col_3":"Xác định tỷ lệ thử, FMEA sơ bộ","col_4":"Đào Hoàng Dương","col_6":"Hoàn thành","col_7":""},
  {"row_number":30,"date":"20–31/01","col_2":"Tuần 4","col_3":"Chốt công thức, lập PR mua hàng","col_4":"Đào Hoàng Dương","col_6":"Hoàn thành","col_7":"Gửi SC báo giá NCC"},
  {"row_number":31,"date":"01–07/02","col_2":"Tuần 5","col_3":"Gửi PR, làm việc NCC","col_4":"Đào Hoàng Dương","col_6":"Đang thực hiện","col_7":""},
  {"row_number":32,"date":"08–14/02","col_2":"Tuần 6","col_3":"Nhận COA, MSDS","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":33,"date":"22–29/02","col_2":"Tuần 8","col_3":"Nguyên liệu về kho, IQC. Chuẩn bị compound","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":34,"date":"01–07/03","col_2":"Tuần 9","col_3":"Compound thử A/B/C","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":35,"date":"08–14/03","col_2":"Tuần 10","col_3":"Đánh giá phân tán, loại công thức kém","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":36,"date":"15–21/03","col_2":"Tuần 11","col_3":"Chốt công thức, chuẩn bị ECN-1","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":37,"date":"22–31/03","col_2":"Tuần 12","col_3":"Phát hành ECN-1","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":38,"date":"01–07/04","col_2":"Tuần 13","col_3":"Họp R&D-KTCN, setup ép","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":39,"date":"08–14/04","col_2":"Tuần 14","col_3":"Ép thử lô T0","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":40,"date":"15–21/04","col_2":"Tuần 15","col_3":"Đánh giá T0, tối ưu ép","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":41,"date":"22–30/04","col_2":"Tuần 16","col_3":"Phát hành ECN-2","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":42,"date":"01–07/05","col_2":"Tuần 17","col_3":"Chạy lô T1 (pilot)","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":43,"date":"08–14/05","col_2":"Tuần 18","col_3":"Gửi mẫu test vi sinh","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":44,"date":"15–21/05","col_2":"Tuần 19","col_3":"Theo dõi test, phân tích chi phí","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":45,"date":"22–31/05","col_2":"Tuần 20","col_3":"Nhận kết quả vi sinh","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":46,"date":"01–07/06","col_2":"Tuần 21","col_3":"Chạy lô T2","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":47,"date":"08–14/06","col_2":"Tuần 22","col_3":"Đánh giá SPC, phế phẩm","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":48,"date":"15–21/06","col_2":"Tuần 23","col_3":"Phát hành ECN-3","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":49,"date":"22–30/06","col_2":"Tuần 24","col_3":"Tổng kết dự án","col_4":"Đào Hoàng Dương","col_6":"","col_7":""},
  {"row_number":50,"date":"Từ 4/1 đến 9/1","col_2":"1","col_3":"Xác định vấn đề phạm vi ứng dụng","col_4":"Nguyễn Văn Linh","col_6":"Hoàn thành","col_7":"Các công đoạn trong sản xuất linh kiện và lắp ráp M25. Giải pháp Buồng sạch ứng dụng trong giai đoạn cuối - lắp ráp thành phẩm M25"},
  {"row_number":51,"date":"Từ 11/1 đến 16/1","col_2":"2","col_3":"Tổng hợp, so sánh cấc giải pháp kháng khuẩn trong sản xuất: Ozone, UV, Buồng sạch","col_4":"Nguyễn Văn Linh","col_6":"Hoàn thành","col_7":"Phương án khả thi nhất: Xây dựng buồng sạch"},
  {"row_number":52,"date":"Từ 1/2 đến 6/2","col_2":"5","col_3":"Rà soát 4M trong sản xuất linh kiện M25","col_4":"Nguyễn Văn Linh","col_6":"Đang thực hiện","col_7":""},
  {"row_number":53,"date":"Từ 8/2 đến 13/2","col_2":"6","col_3":"Bổ sung quy trình, thiết bị cần trong sản xuất: găng tay, cồn, bàn inox,...","col_4":"Nguyễn Văn Linh","col_6":"Đang thực hiện","col_7":""},
  {"row_number":54,"date":"Từ 22/2 đến 27/2","col_2":"8","col_3":"Xây dựng sơ đồ, nguyên lý triển khai cho ý tưởng Buồng sạch","col_4":"Nguyễn Văn Linh","col_6":"Đang thực hiện","col_7":""},
  {"row_number":55,"date":"Từ 15/3 đến 20/3","col_2":"11","col_3":"Liên hệ trao đổi NCC lên giải pháp chi tiết","col_4":"Nguyễn Văn Linh","col_6":"","col_7":""},
  {"row_number":56,"date":"Từ 5/4 đến 10/4","col_2":"14","col_3":"Tổng hợp, so sánh các giải pháp NCC - chọn lựa phương án khả thi và đề xuất chủ trương","col_4":"Nguyễn Văn Linh","col_6":"","col_7":""},
  {"row_number":57,"date":"Từ 19/4 đến 24/4","col_2":"16","col_3":"Đề xuất phê duyệt chủ trương triển khai","col_4":"Nguyễn Văn Linh","col_6":"","col_7":""},
  {"row_number":58,"date":"Từ 17/5 đến 22/5","col_2":"20","col_3":"Triển khai lắp đặt và thử nghiệm trong sản xuất","col_4":"Nguyễn Văn Linh","col_6":"","col_7":""},
  {"row_number":59,"date":"Từ 21/6 đến 26/6","col_2":"25","col_3":"Vận hành và theo dõi","col_4":"Nguyễn Văn Linh","col_6":"","col_7":""},
  {"row_number":60,"date":"01–05/01/2026","col_2":"Tuần 1","col_3":"Kick-off dự án, xác định vị trí ứng dụng","col_4":"Nguyễn Thế Việt","col_6":"Hoàn thành","col_7":""},
  {"row_number":61,"date":"06–12/01/2026","col_2":"Tuần 2","col_3":"Nghiên cứu công nghệ UVC","col_4":"Nguyễn Thế Việt","col_6":"Hoàn thành","col_7":""},
  {"row_number":62,"date":"13–19/01/2026","col_2":"Tuần 3","col_3":"Benchmark & tiêu chí chọn NCC, Lập DFMEA","col_4":"Nguyễn Thế Việt","col_6":"Hoàn thành","col_7":""},
  {"row_number":63,"date":"20–31/01/2026","col_2":"Tuần 4","col_3":"Chốt yêu cầu kỹ thuật, tham khảo các bộ phận chức năng khác","col_4":"Nguyễn Thế Việt","col_6":"Hoàn thành","col_7":""},
  {"row_number":64,"date":"01–07/02/2026","col_2":"Tuần 5","col_3":"Tìm kiếm NCC UVC và làm đề nghị đặt hàng. Tìm kiếm đơn vị phân tích vi sinh.","col_4":"Nguyễn Thế Việt","col_6":"Hoàn thành","col_7":""},
  {"row_number":65,"date":"08–14/02/2026","col_2":"Tuần 6","col_3":"Lập mindmap đánh giá thử nghiệm. Gửi mẫu đánh giá cho DQA và NCTN","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":66,"date":"22–29/02/2026","col_2":"Tuần 8","col_3":"Tổng hợp báo cáo, test các hạng mục rủi ro cao.","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":67,"date":"01–07/03/2026","col_2":"Tuần 9","col_3":"Lắp linh kiện trên máy M25 đánh giá cụ thể","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":68,"date":"08–14/03/2026","col_2":"Tuần 10","col_3":"Thực hiện test bền UVC","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":69,"date":"15–21/03/2026","col_2":"Tuần 11","col_3":"Lắp máy M25 sử dụng UVC để uống trải nghiệm hàng ngày","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":70,"date":"22–31/03/2026","col_2":"Tuần 12","col_3":"Thu thập dữ liệu phản hồi về màu, mùi vị khi sử dụng linh kiện. Lập TCKT","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":71,"date":"01–07/04/2026","col_2":"Tuần 13","col_3":"Test kháng khuẩn ban đầu. Ban hành TCKT, cài giá trên SAP","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":72,"date":"08–14/04/2026","col_2":"Tuần 14","col_3":"Chạy máy mốc 1 tháng.","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":73,"date":"15–21/04/2026","col_2":"Tuần 15","col_3":"Test kháng khuẩn sau 1 tháng","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":74,"date":"22–30/04/2026","col_2":"Tuần 16","col_3":"Tổng hợp kết quả phân tích và bảng đánh giá trải nghiệm máy.","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":75,"date":"01–07/05/2026","col_2":"Tuần 17","col_3":"Ban hành ECN chuyển đổi. Đề xuất KHSX lên lịch đặt hàng","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":76,"date":"08–14/05/2026","col_2":"Tuần 18","col_3":"Chạy lô T0","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":77,"date":"15–21/05/2026","col_2":"Tuần 19","col_3":"Đánh giá T0 cho NCTN và DQA","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":78,"date":"22–31/05/2026","col_2":"Tuần 20","col_3":"Lên lịch sản xuất chạy lô T1.","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":79,"date":"01–07/06/2026","col_2":"Tuần 21","col_3":"Chạy lô T1","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":80,"date":"08–14/06/2026","col_2":"Tuần 22","col_3":"Đánh giá lô T1","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":81,"date":"15–21/06/2026","col_2":"Tuần 23","col_3":"Hoàn thiện hồ sơ sản xuất","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":82,"date":"22–30/06/2026","col_2":"Tuần 24","col_3":"Chuyển giao hồ sơ xuống nhà máy.","col_4":"Nguyễn Thế Việt","col_6":"Đang thực hiện","col_7":""},
  {"row_number":83,"date":"Từ 11/1 đến 16/1","col_2":"2","col_3":"Rà soát sơ đồ nguyên lý của sản phẩm. Phân tích, tính toán, mô phỏng thời gian, thể tích nước cần xả rửa ban đầu và định kỳ","col_4":"Nguyễn Văn Hiếu","col_6":"Hoàn thành","col_7":"Theo TC: Thể tích nước xả rửa (30-40)L. Thời gian xả rửa ban đầu 2h. Định kỳ 3 phút sau 24h."},
  {"row_number":84,"date":"Từ 25/1 đến 30/1","col_2":"4","col_3":"Tìm hiểu màng UF, thử nghiệm loại bỏ cặn bẩn mạt than, thử nghiệm trên mẫu in 3D","col_4":"Nguyễn Văn Hiếu","col_6":"Đang thực hiện","col_7":"Màng UF loại bỏ mạt than tốt hơn lõi pp nano. Đang test bền."},
  {"row_number":85,"date":"Từ 8/2 đến 13/2","col_2":"6","col_3":"Thử nghiệm giả lập điều kiện nhiễm khuẩn. Thử nghiệm tính năng lọc và xả rửa tự động","col_4":"Nguyễn Văn Hiếu","col_6":"Đang thực hiện","col_7":""},
  {"row_number":86,"date":"Từ 22/2 đến 27/2","col_2":"8","col_3":"Theo dõi kết quả thử nghiệm và test bền","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":87,"date":"Từ 8/3 đến 13/3","col_2":"10","col_3":"Đàm phán NCC mở khuôn nắp chụp màng UF. Đàm phán NCC gia công mạch in phíp đồng","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":88,"date":"Từ 22/3 đến 27/3","col_2":"12","col_3":"Lấy mẫu S3 về đánh giá lắp ráp thực tế và thử nghiệm tại lab","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":89,"date":"Từ 5/4 đến 10/4","col_2":"14","col_3":"Đánh giá mẫu thành phẩm S3 trên sản phẩm","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":90,"date":"Từ 12/4 đến 17/4","col_2":"15","col_3":"Trao đổi NCC, lấy mẫu T1 hoặc cải tiến vẫn đề sau T0","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":91,"date":"Từ 26/4 đến 1/5","col_2":"17","col_3":"Ban hành TCKT + ký NCC + áp dụng ECN lô nhỏ","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":92,"date":"Từ 10/5 đến 15/5","col_2":"19","col_3":"Nhập hàng T0 áp dụng sản xuất lắp ráp T0 tại TCM. Đánh giá mẫu T0 thành phẩm","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":93,"date":"Từ 24/5 đến 29/5","col_2":"21","col_3":"Gửi đơn đặt hàng T1","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":94,"date":"Từ 7/6 đến 12/6","col_2":"23","col_3":"Sản xuất lô T1 tại TCM đánh giá mức độ ổn định và chất lượng sản phẩm","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""},
  {"row_number":95,"date":"Từ 14/6 đến 19/6","col_2":"24","col_3":"Hoàn thiện hồ sơ, ban giao các phòng ban sản xuất","col_4":"Nguyễn Văn Hiếu","col_6":"","col_7":""}
];

